name: ci

on:
  pull_request:
    branches:
    - master

jobs:
  test_go:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v1
      with:
        go-version:  '1.11'
    - name: Test go packages
      run: make test-go
      env:
        CERTS_PASS: ${{ secrets.CERTS_PASS }}
        DECORD_KEY: ${{ secrets.DECORD_KEY }}
